#!/bin/bash
#Git Ignore
##VSCode 


echo "

### VSCODE
## Ignore VSCode temporary files, build results, and
## files generated by popular VSCode add-ons.
##
## Get latest from https://github.com/github/gitignore/blob/master/Global/VisualStudioCode.gitignore

.vscode/*
!.vscode/settings.json
!.vscode/tasks.json
!.vscode/launch.json
!.vscode/extensions.json
*.code-workspace

# Local History for Visual Studio Code
.history/" >> .gitignore 